version: "3.5"
x-buildargs:
    &default-buildargs
    BUILD_BASE: base
volumes:
    temp_data:
services:
    dev:
        image: website/app:dev
        ports:
            - "5105:80"    # Vanilla watch `npm run watch`
            - "5155:5155"  # Hot reloading server `npm run reloader`
        build:
            context: .
            target: src
            args: *default-buildargs
        volumes:
            - "${FOLDER_LOCATION:-.}/src:/home/app/src"
            - "${FOLDER_LOCATION:-.}/server:/home/app/server"
            #- "${FOLDER_LOCATION:-.}/../notes:/home/app/server/static/md"
        env_file:
            - "${COMPOSE_ENV_FILE:-.env.tmpl}"
        environment:
            DEV_DATABASE_URL_ORIGIN: "mongodb://mongodb:27017"
            DEV_ENV: "true"
            ENABLE_DB: "false"
            LIVE_RELOADER_PORT: 5055
            LOG_EVERY_NUM_CHECKS: 5
            #PM2_TZ: "America/Los_Angeles"
        ###! Uncomment to bring up the mongodb service
        ###! Also set ENABLE_DB to "true" - See server/routes.js to adjust behavior
        #depends_on:
        #    - mongodb
 
    #### Dev DB service ===
    mongodb:
        image: mongo:4.4.6
        ports: ["27017:27017"]
        restart: on-failure
        environment:
            MONGO_INITDB_DATABASE: "${MONGO_DB_NAME:-mongo}"
        volumes:
            - temp_data:/data/db
    ###############################################################
    ###############################################################
    main:
        image: registry.codeopensrc.com/kc/website/app:0.10.0
        ports: ["5100:80"]
        labels: ["com.codeopensrc.consul=website"]
        build:
            context: .
            target: prod
            args: *default-buildargs
        env_file:
            - "${COMPOSE_ENV_FILE:-.env.tmpl}"
        environment:
            AUTH_URL:               "${AUTH_URL}"
            ENABLE_DB:              "false"
###############################################################
###############################################################
    #### WIP =======
    # unitydev:
    #     build:
    #         context: .
    #         target: prod
    #         dockerfile: Dockerfile-Unity
    #     image: website/unity:dev
    #     ports: ["7777:7777"]
    #     entrypoint: ["./server/game.x86_64", "-nographics", "-batchmode"]
    #     depends_on:
    #         - dev
    #### WIP ======
    # unity:
    #     build:
    #         context: .
    #         target: prod
    #         dockerfile: Dockerfile-Unity
    #     image: registry.codeopensrc.com/kc/website/unity:0.2.7
    #     ports: ["7777:7777"]
    #     entrypoint: ["./server/game.x86_64", "-nographics", "-batchmode"]
    #     depends_on:
    #         - main
