version: "3.5"
x-buildargs:
    &default-buildargs
    BASE_IMAGE: alpine
    BASE_IMAGE_TAG: 3.14
    NODE_VER: 14.17.6-r0
    NPM_VER: 7.17.0-r0
    PM2_VER: 5.1.1
volumes:
    temp_data:
services:
    dev:
        image: website/app:dev
        ports: ["5105:80"]
        build:
            context: .
            target: src
            args: *default-buildargs
        volumes:
            - "${FOLDER_LOCATION:-.}/src:/home/app/src"
            - "${FOLDER_LOCATION:-.}/server:/home/app/server"
            - "${FOLDER_LOCATION:-.}/docker-compose.yml:/home/app/docker-compose.yml"
            #- "${FOLDER_LOCATION:-.}/../notes:/home/app/server/static/md"
        environment:
            DEV_DATABASE_URL: "mongodb://mongodb:27017/${MONGO_DB_NAME:-mongo}"
            LOG_EVERY_NUM_CHECKS: 5
            DEV_ENV:          "true"
        depends_on:
            - mongodb
    #### Dev DB service ===
    mongodb:
        image: mongo:4.4.6
        ports: ["27017:27017"]
        restart: on-failure
        environment:
            MONGO_INITDB_DATABASE: "${MONGO_DB_NAME:-mongo}"
        volumes:
            - temp_data:/data/db
    ###############################################################
    ###############################################################
    main:
        image: registry.codeopensrc.com/kc/website/app:0.6.1-d0e19d5
        ports: ["5100:80"]
        labels: ["com.codeopensrc.consul=website"]
        build:
            context: .
            target: prod
            args: *default-buildargs
        environment:
            CONSUL_SERVICE_NAME:    "website"
            REGISTER_SERVICE:       "true"
            AUTH_URL:               "${AUTH_URL}"
        ## Docker Swarm - https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy
        ## deploy:
###############################################################
###############################################################
    #### WIP =======
    # unitydev:
    #     build:
    #         context: .
    #         target: prod
    #         dockerfile: Dockerfile-Unity
    #     image: website/unity:dev
    #     ports: ["7777:7777"]
    #     entrypoint: ["./server/game.x86_64", "-nographics", "-batchmode"]
    #     depends_on:
    #         - dev
    #### WIP ======
    # unity:
    #     build:
    #         context: .
    #         target: prod
    #         dockerfile: Dockerfile-Unity
    #     image: registry.codeopensrc.com/kc/website/unity:0.2.7
    #     ports: ["7777:7777"]
    #     entrypoint: ["./server/game.x86_64", "-nographics", "-batchmode"]
    #     depends_on:
    #         - main
