app:
  enabled: true
  replicaCount: 1
  image:
    repository: registry.codeopensrc.com/kc/website/app
  secretStringData:
    MONGO_DB_NAME: "website"
    BLOG_KEY: "secret_value"
  configMapData:
    DEV_DATABASE_URL_ORIGIN: "mongodb://website-db:27017"
    ENABLE_DB:           "false"
    AUTH_URL:             ""
    GITLAB_API_URL:       ""
db:
  enabled: false
