{{- if .Values.secretStringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
    {{- with .Values.ciLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretStringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
