{{- if eq (default false .Values.useStatefulSet) true }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
    {{- with .Values.ciLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.configMapData }}
    configHash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    {{- end }}
    {{- range .Values.createAndAttachExtraConfigMaps }}
    {{ .name }}Hash: {{ include (print $.Template.BasePath "/auxConfigmap.yaml") $ | sha256sum }}
    {{- end }}
    {{- range .Values.attachExtraConfigMaps }}
    {{- if (lookup "v1" "ConfigMap" $.Release.Namespace .name) }}
    {{ .name }}Hash: {{ (lookup "v1" "ConfigMap" $.Release.Namespace .name).data | toString | sha256sum }}
    {{- end }}
    {{- end }}
    {{- if .Values.secretStringData }}
    secretHash: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    {{- end }}
    {{- if .Values.dotEnvFile }}
    dotEnvFileHash: {{ include (print $.Template.BasePath "/dotEnvSecret.yaml") . | sha256sum }}
    {{- end }}
    {{- range .Values.createAndAttachExtraSecrets }}
    {{ .name }}Hash: {{ include (print $.Template.BasePath "/auxSecret.yaml") $ | sha256sum }}
    {{- end }}
    {{- range .Values.attachExtraSecrets }}
    {{- if (lookup "v1" "Secret" $.Release.Namespace .name) }}
    {{ .name }}Hash: {{ (lookup "v1" "Secret" $.Release.Namespace .name).stringData | toString | sha256sum }}
    {{- end }}
    {{- end }}
    {{- with .Values.ciAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "website.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "website.fullname" . }}
  {{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
  minReadySeconds: 3
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "website.selectorLabels" . | nindent 8 }}
        {{- with .Values.ciLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.configMapData }}
        configHash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- range .Values.createAndAttachExtraConfigMaps }}
        {{ .name }}Hash: {{ include (print $.Template.BasePath "/auxConfigmap.yaml") $ | sha256sum }}
        {{- end }}
        {{- range .Values.attachExtraConfigMaps }}
        {{- if (lookup "v1" "ConfigMap" $.Release.Namespace .name) }}
        {{ .name }}Hash: {{ (lookup "v1" "ConfigMap" $.Release.Namespace .name).data | toString | sha256sum }}
        {{- end }}
        {{- end }}
        {{- if .Values.secretStringData }}
        secretHash: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.dotEnvFile }}
        dotEnvFileHash: {{ include (print $.Template.BasePath "/dotEnvSecret.yaml") . | sha256sum }}
        {{- end }}
        {{- range .Values.createAndAttachExtraSecrets }}
        {{ .name }}Hash: {{ include (print $.Template.BasePath "/auxSecret.yaml") $ | sha256sum }}
        {{- end }}
        {{- range .Values.attachExtraSecrets }}
        {{- if (lookup "v1" "Secret" $.Release.Namespace .name) }}
        {{ .name }}Hash: {{ (lookup "v1" "Secret" $.Release.Namespace .name).stringData | toString | sha256sum }}
        {{- end }}
        {{- end }}
        {{- with .Values.ciAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "website.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                {{- $selectorLabelList := regexSplit "\n" (include "website.selectorLabels" .) -1 }}
                {{- range $ind, $label := $selectorLabelList }}
                - key: {{ regexSplit ":" $label -1 | first | trim }}
                  operator: In
                  values:
                  - {{ regexSplit ":" $label -1 | last | trim }}
                {{- end }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ include "website.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: 
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          ports:
            {{- range .Values.containerPorts }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.containerProbe }}
          livenessProbe:
            httpGet:
              path: {{ default "/" .Values.containerProbe.path }}
              port: http
              {{- with .Values.containerProbe.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            failureThreshold: 50
          {{- end }}
          {{- if .Values.containerProbe }}
          readinessProbe:
            httpGet:
              path: {{ default "/" .Values.containerProbe.path }}
              port: http
              {{- with .Values.containerProbe.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            initialDelaySeconds: 5
          {{- end }}
          envFrom:
            {{- if .Values.secretStringData }}
            - secretRef:
                name: {{ include "website.fullname" . }}
            {{- end }}
            {{- range concat .Values.createAndAttachExtraSecrets .Values.attachExtraSecrets }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
            {{- if .Values.configMapData }}
            - configMapRef:
                name: {{ include "website.fullname" . }}
            {{- end }}
            {{- range concat .Values.createAndAttachExtraConfigMaps .Values.attachExtraConfigMaps }}
            - configMapRef:
                name: {{ .name }}
            {{- end }}
            {{- if .Values.dotEnvFile }}
            - secretRef:
                name: {{ include "website.fullname" . }}-dotenv
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.lifecyclePostStartCommand }}
          lifecycle:
            postStart:
              exec:
                command: 
                  {{- toYaml .Values.lifecyclePostStartCommand | nindent 18 }}
          {{- end }}
          volumeMounts:
            {{- range .Values.volumeMounts }}
            {{- if ne .attach false }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- range .Values.volumeClaimMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ default (include "website.fullname" $) .name }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
        {{- range .Values.additionalContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          command: 
            {{- toYaml .command | nindent 12 }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- range $.Values.volumeClaimMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ default (include "website.fullname" $) .name }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        {{- range .Values.volumeMounts }}
        {{- if .mountType }}
        - name: {{ .name }}
          {{- toYaml .mountType | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if semverCompare ">=1.25-0" .Capabilities.KubeVersion.GitVersion }}
      {{- if .Values.persistence.statefulset.persistentVolumeClaimRetentionPolicy }}
      persistentVolumeClaimRetentionPolicy:
        {{- toYaml .Values.persistence.statefulset.persistentVolumeClaimRetentionPolicy | nindent 8 }}
      {{- end }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ default (include "website.fullname" $) .Values.persistence.statefulset.volumeClaimTemplate.name }}
      spec:
        {{- toYaml .Values.persistence.statefulset.volumeClaimTemplate | nindent 8 }}
{{- end }}
